{
    "name": "Voucher Management System",
    "summary": "Voucher Management System",
    "version": "13.0.1.0.0",
    "author": "Wahyu Hidayat, "
              "WEHA",
    "category": "Voucher",
    "website": "https://www.weha-id.com",
    "license": "AGPL-3",
    'data': [
        'data/weha_voucher_data.xml',
        #'data/weha_voucher_order_line_data.xml',
        #'data/weha_voucher_order_data.xml',
        #'data/weha_voucher_request_data.xml',
        #'data/weha_voucher_allocate_data.xml',
        #'data/weha_voucher_scrap_data.xml',
        #'data/weha_voucher_issuing_data.xml',
        #'data/weha_voucher_return_data.xml',
        'data/weha_voucher_api_data.xml',
        #'data/weha_voucher_config_data.xml',
        'data/ir_config_param.xml',
        'security/weha_voucher_security.xml',
        'security/ir.model.access.csv',
        'views/res_users.xml',
        'views/operating_unit_view.xml',
        'views/weha_voucher_menu.xml',
        'wizard/weha_select_order_line_wizard_view.xml',
        'wizard/weha_received_request_wizard_view.xml',
        'wizard/weha_received_allocate_wizard_view.xml',
        'wizard/weha_scrap_wizard_view.xml',
        'wizard/weha_received_return_wizard_view.xml',
        'wizard/weha_received_scrap_wizard_view.xml',
        'wizard/weha_received_issuing_wizard_view.xml',
        'wizard/weha_import_voucher_issuing_wizard_view.xml',
        'wizard/weha_report_voucher_stock_wizard_view.xml',
        'wizard/weha_report_voucher_transaction_view.xml',
        'wizard/weha_received_order_wizard_view.xml',
        'wizard/weha_return_reason_wizard_view.xml',
        'wizard/weha_import_voucher_legacy_issuing_wizard_view.xml',
        'wizard/weha_import_voucher_allocate_wizard_view.xml',
        'views/weha_voucher_stage_view.xml',
        'views/weha_voucher_order_view.xml',
        'views/weha_voucher_order_line_view.xml',
        'views/weha_voucher_allocate_view.xml',
        'views/weha_voucher_allocate_template.xml',
        'views/weha_voucher_allocate_report.xml',
        'views/weha_voucher_request_view.xml',
        'views/weha_voucher_request_template.xml',
        'views/weha_voucher_request_report.xml',
        # 'views/weha_voucher_request_line_view.xml',
        'views/weha_voucher_number_ranges_view.xml',
        'views/weha_voucher_return_view.xml',
        'views/weha_voucher_return_line_view.xml',
        'views/weha_voucher_allocate_view.xml',
        'views/weha_voucher_allocate_template.xml',
        'views/weha_voucher_allocate_report.xml',
        # 'views/weha_voucher_return_line_view.xml',
        #'views/weha_voucher_allocate_line_view.xml',
        'views/weha_voucher_stock_transfer_view.xml',
        'views/weha_voucher_stock_transfer_line_view.xml',
        'views/weha_voucher_config_code_view.xml',
        'views/weha_voucher_transaction_type_view.xml',
        'views/weha_voucher_config_mapping_pos_view.xml',
        'views/weha_voucher_config_mapping_sku_view.xml',
        'views/weha_voucher_config_location_view.xml',
        #'views/weha_voucher_config_number_range_view.xml',
        'views/weha_voucher_config_terms_view.xml',
        'views/weha_voucher_config_type_view.xml',
        'views/weha_voucher_config_promo_view.xml',
        'views/weha_voucher_config_year_view.xml',
        'views/weha_voucher_config_tender_type_view.xml',
        'views/weha_voucher_config_bank_category_view.xml',
        'views/weha_voucher_return_stage_view.xml',
        'views/weha_voucher_allocate_stage_view.xml',
        'views/weha_voucher_scrap_stage_view.xml',
        'views/weha_voucher_scrap_view.xml',
        # 'views/weha_voucher_scrap_line_view.xml',
        'views/weha_voucher_issuing_stage_view.xml',
        'views/weha_voucher_issuing_view.xml',
        'views/weha_voucher_stock_transfer_stage_view.xml',
        'views/weha_voucher_code_minimum_stock_view.xml',
        'views/res_company_settings_view.xml',
        'views/weha_voucher_dashboard_view.xml',   
        'views/weha_voucher_api_view.xml',
        'report/weha_report_voucher_stock_template.xml',
        'report/weha_report_voucher_transaction_template.xml',
        
    ],
    "depends": [
        'base',
        'mail',
        'operating_unit',
        'board'
    ],
    'qweb': ["static/src/xml/voucher_dashboard.xml"],
    "installable": True,
    "application": True,
}
